### ISSUE TITLE
decoder model weight

### ISSUE THREAD

**Issue by xinyuanzhu** [mahdip72/prot2token#2]
I am currently working with your project and would like to know how I can obtain the weights for the decoder model.
Could you please provide guidance or instructions on how to access these weights? Any help would be greatly appreciated!
Thank you for your time.

**Comment by mahdip72** [comment]
Hello @xinyuanzhu 
Thank you for your interest in our work!

To access the weights of a pre-trained model, you can extract them with the following code snippet:

```python
model_checkpoint = torch.load(configs.resume.resume_path, map_location='cpu')

# Extracting the pre-trained state dictionary
pretrained_state_dict = model_checkpoint['model_state_dict']
```

The pretrained_state_dict will contain all the weights, where keys starting with decoder refer to the decoder's weights.

If you need further guidance, feel free to reach out.
